### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by valentinkiryanski** [amonod/hdrplus-python#1]
Hello! Please if you can make an ios camera app that shoots a burst of dng raw images and then performs hdr plus processing and. saves the final processed photo. Thank you for understanding me!

**Comment by amonod** [comment]
Thank you for your suggestion. I'm afraid this would require extensive ios camera & app development knowledge (which I don't have), and probably a lot of additional development time for optimization, as the code is not designed for mobile and processing times are not suitable for real time execution.
Since the code is freely available, you could of course ask anybody else to do that for you.

**Comment by valentinkiryanski** [comment]
I asked but they probably wont do a good job of it. Also can you please make a windows app or a simplified version for online HDR+ processing like the program seen in your paper burst photography for high dynamic range and low light imaging on mobile cameras because the one that is now online i cant understand how to use it and it always gives me an error that there should be atleast one raw dng image in the burst which all of the images that i imported are dng?
